from enum import Enum

class Equity(Enum):
    BAC = "Bank of America Corporation"
    BCS = "Barclays PLC"
    BK = "The Bank of New York Mellon Corporation"
    BNPP = "BNP Paribas SA"
    BX = "The Blackstone Group Inc."
    CS = "Credit Suisse Group AG"
    DBKGN = "Deutsche Bank AG"
    FMCC = "Freddie Mac"
    GS = "The Goldman Sachs Group, Inc."
    HSBA = "HSBC Holdings plc"
    ING = "ING Group N.V."
    JPM = "JPMorgan Chase & Co."
    KKR = "KKR & Co. Inc."
    LEHMQ = "Lehman Brothers Holdings Inc. (Bankrupt)"
    MCO = "Moody's Corporation"
    MS = "Morgan Stanley"
    RBS = "The Royal Bank of Scotland Group plc"
    RY = "Royal Bank of Canada"
    SOCGEN = "Société Générale S.A."
    UBSN = "UBS Group AG"
    UTX = "United Technologies Corporation"
    WFC = "Wells Fargo & Co."
    BMWG = "Bayerische Motoren Werke AG (BMW)"
    DAIGN = "Daimler AG (Mercedes-Benz)"
    FIA = "Ferrari N.V."
    GM = "General Motors Company"
    HMC = "Honda Motor Co., Ltd."
    NISSAN = "Nissan Motor Co., Ltd."
    RENA = "Renault S.A."
    TM = "Toyota Motor Corporation"
    VOWG = "Volkswagen AG"
    AAPL = "Apple Inc."
    AMZN = "Amazon.com, Inc."
    BBY = "Best Buy Co., Inc."
    CSCO = "Cisco Systems, Inc."
    EBAY = "eBay Inc."
    EC = "Ecopetrol S.A."
    ERICB = "Telefonaktiebolaget LM Ericsson"
    GART = "Gartner, Inc."
    NER = "Newmont Corporation"
    GE = "General Electric Company"
    GOOG = "Alphabet Inc. (Google)"
    HPQ = "HP Inc."
    IBM = "International Business Machines Corporation"
    INTC = "Intel Corporation"
    MA = "Mastercard Incorporated"
    MSFT = "Microsoft Corporation"
    NOK = "Nokia Corporation"
    SSNLF = "Samsung Electronics Co., Ltd."
    SNE = "Sony Group Corporation"
    TVS = "The Travelers Companies, Inc."
    YHOO = "Yahoo! Inc. (Now part of Verizon Communications Inc.)"
    COST = "Costco Wholesale Corporation"
    GPS = "The Gap, Inc."
    HD = "The Home Depot, Inc."
    JCP = "J.C. Penney Company, Inc. (Bankrupt)"
    TGT = "Target Corporation"
    WMT = "Walmart Inc."
    AIG = "American International Group, Inc."
    BA = "The Boeing Company"
    DAL = "Delta Air Lines, Inc."
    EAD = "Airbus SE"
    FDX = "FedEx Corporation"
    UAL = "United Airlines Holdings, Inc."
    UPS = "United Parcel Service, Inc."
    XP = "XP Inc."
    BBRY = "BlackBerry Limited"
    BP = "BP p.l.c."
    BRKA = "Berkshire Hathaway Inc. (Class A shares)"
    CAT = "Caterpillar Inc."
    CEOS = "CNOOC Limited"
    CVX = "Chevron Corporation"
    ISM = "IQVIA Holdings Inc."
    JNJ = "Johnson & Johnson"
    KO = "The Coca-Cola Company"
    MCD = "McDonald's Corporation"
    PEP = "PepsiCo, Inc."
    PFE = "Pfizer Inc."
    PG = "Procter & Gamble Company"
    RDSA = "Royal Dutch Shell plc (Class A shares)"
    SBUX = "Starbucks Corporation"
    XOM = "Exxon Mobil Corporation"
    AA = "Alcoa Corporation"
    BLT = "BHP Group plc"
    BMO = "Bank of Montreal"
    RIO = "Rio Tinto Group"
    VOD = "Vodafone Group Plc"
    VZ = "Verizon Communications Inc."

    @classmethod
    def get_all_keys(cls):
        return [equity.name for equity in cls]

    @classmethod
    def get_value_by_key(cls, key):
        try:
            return cls[key].value
        except KeyError:
            return None
